### ISSUE TITLE
Please check fusiegemeenten 

### ISSUE THREAD

**Issue by baksand** [openstate/open-raadsinformatie#442]
Kind reminder, please check all the fusiegemeenten.  

Example, gemeente Voorne aan Zee

thanks

**Comment by joepio** [comment]
We have 2 possible solutions:

1. Keep the old municipalities, add the fusion one through the existing process. This means we end up with 450+ municipalities, which includes those that no longer exist.
2. We bring the indexed data from the old municipality to the new fusion municipality.


@breyten do you think solution 2 is feasible?

**Comment by joepio** [comment]
We need to check all fused municipalities. If the new fusion municipality is added to sources, we move the documents to the new fusion municipality. If the fusion municipality isn't in the sources yet, we tag @baksand

**Comment by joepio** [comment]
Additionally, we sometimes need to import municipalities that no longer exist - by adding them to a different index. For example, add Landerd and Uden to Maashorst

> Nu is het zo dat de gemeente Maashorst een fusie is van de gemeenten Landerd en Uden en sinds 2022 bestaat. Heeft het zin om ook de stukken van Landerd en Uden in de ORI op te nemen? Deze stukken staan nog altijd op het RIS van Landerd (https://landerd.bestuurlijkeinformatie.nl/) en Uden (https://uden.bestuurlijkeinformatie.nl/). Beide gemeenten werkten met iBabs. Anders ontbreken alle stukken van vóór 2022.

If I add sources for Landerd and Uden, it will create indexes. How should I do this? 

We currently have this entry:

```yml
  maashorst:
    key: maashorst
    ibabs_sitename: maashorst
    allmanak_id: 28523626
    cbs_id: GM1991
    <<: *ibabs
```

Would this add to the same index if I add it to the yml? 

```yml
  maashorst:
    key: maashorst
    # only this value is different!
    ibabs_sitename: landerd
    allmanak_id: 28523626
    cbs_id: GM1991
    <<: *ibabs
```
