### ISSUE TITLE
Municipalities currently switched off

### ISSUE THREAD

**Issue by robvandijk** [openstate/open-raadsinformatie#509]
The following municipalities have been switched off in the past due to errors - probably because they switched suppliers. They are listed below under the `old` suppliers.

## Gemeenteoplossingen:
- borne
- beemster
- midden-groningen
- drechtsteden
- schiermonnikoog
- beuningen
- veldhoven

## ibabs:
- dantumadiel
- dronten
- heeze_leende
- cranendonck
- oostzaan

## notubiz:
- culemborg
- enkhuizen
- tilburg

**Comment by joepio** [comment]
## GO

- Borne: [Moved to ibabs](https://borne.bestuurlijkeinformatie.nl/People)
- Beemster: Still [seems to be](https://beemsterraadsinformatie.purmerend.nl/vergaderingen) on GO, but have a new base URL (used to be `https://gemeenteraad.borne.nl/`)
- Midden-Gronings: swtiched [to Notubiz](https://midden-groningen.raadsinformatie.nl/).
- Drechtsteden: [new URL](https://raad.dordrecht.nl/api)
- Schiermonnikoog: moved [to ibabs](https://schiermonnikoog.bestuurlijkeinformatie.nl/)
- Beuningen: moved [to ibabs](https://beuningen.bestuurlijkeinformatie.nl/Calendar)
- Veldhoven: moved [to notubiz](https://veldhoven.raadsinformatie.nl/)

## ibabs

- Dantumadiel: updated [ibabs sitename](https://gemeentedantumadiel.bestuurlijkeinformatie.nl/Calendar)
-

**Comment by joepio** [comment]
@robvandijk could you take a look at what's going on with the three failed ibabs municipalities? Their source data seems fine (see above).

**Comment by robvandijk** [comment]
@joepio   The `allmanak_id` for `drechtsteden` is not correct. Drechtsteden is not listed at all in the Allmanak.

Should this be simply Dordrecht, with `allmanak_id=40563`?

**Comment by joepio** [comment]
> @joepio The `allmanak_id` for `drechtsteden` is not correct. Drechtsteden is not listed at all in the Allmanak.
> 
> Should this be simply Dordrecht, with `allmanak_id=40563`?

Hmmm, not sure if that is the same. But sounds like a decent fallback!

**Comment by robvandijk** [comment]
Just to be sure: so change
```
  drechtsteden:
    key: drechtsteden
    base_url: "https://raad.dordrecht.nl/api"
    allmanak_id: 24943500
    <<: *go

```
into:
```
  dordrecht:
    key: dordrecht
    base_url: "https://raad.dordrecht.nl/api"
    allmanak_id: 40563
    <<: *go

```
?
